# Generated by Django 2.2 on 2020-04-15 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingPlatform',
            fields=[
                ('gaming_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('relic_id', models.AutoField(primary_key=True, serialize=False)),
                ('relic_name', models.CharField(max_length=32, unique=True)),
                ('wiki_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RunType',
            fields=[
                ('runTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(choices=[('OO', 'One by One'), ('TT', 'Two by Two'), ('FF', 'Four by Four')], max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='beta_tester',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warframe_account_verification_code',
            field=models.CharField(default=user.models._generate_warframe_account_verification_code, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='WarframeAccount',
            fields=[
                ('warframe_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('gaming_platform_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.GamingPlatform')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('players_in_group', models.IntegerField()),
                ('host_user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('relic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Relic')),
                ('run_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.RunType')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('email_verification_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_verification_code', models.CharField(default=user.models._generate_email_verification_code, max_length=32)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
